### ISSUE TITLE
Check why the xrefsBatch call is not working on swagger

### ISSUE THREAD

**Issue by nunogit** [bridgedb/swagger-webservice#12]
@egonw @AlexanderPico 

Based on https://github.com/bridgedb/BridgeDb/issues/137 

When doing the call as a "POST" (for xrefsBatch) the response is invalid. Digging further one sees that request is sent with the  "OPTIONS" verb instead of "POST":
 
Debug information from browser:
```
Request URL: https://webservice.bridgedb.org/Human/xrefsBatch/L
Request Method: OPTIONS
Status Code: 405 The method specified in the request is not allowed for the resource identified by the request URI
Remote Address: 35.157.241.83:443
Referrer Policy: no-referrer-when-downgrade
```

Check if this is either a configuration file error or if the swagger javascript library that renders the GUI and handles the queries needs to be updated.

**Comment by AlexanderPico** [comment]
Thanks for looking into this @nunogit . I'm unable to get any webservice returns at the moment; presumably you have the site down while working on this.

Let me know when it's ready to test.

**Comment by egonw** [comment]
Yes, same observation... Jenkins has been nagging about it also.

**Comment by nunogit** [comment]
@AlexanderPico you can test now, please. The server just died. I will try to discover the reason.

**Comment by AlexanderPico** [comment]
Getting returns for GET now, but still not getting proper response for POST by Swagger, curl or call from Java application (WikiPathways app for Cytoscape):

```
curl -X POST --header 'Content-Type: text/html' --header 'Accept: /' -d '1234' 'https://webservice.bridgedb.org/Human/xrefsBatch/L'
```
```
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<h3>The server has not found anything matching the request URI</h3><p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.5">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>
```

**Comment by AlexanderPico** [comment]
Was there perhaps a special handling via an .htaccess file on the old server?  Just guessing...

**Comment by AlexanderPico** [comment]
Yay, it's working again! Thanks!

**Comment by egonw** [comment]
The problem seems to have to do with the webservice running BridgeDb 2.0 where 2.3.3 does not work. This will be explored.
