### ISSUE TITLE
Solve problem with xrefsBatch not working

### ISSUE THREAD

**Issue by nunogit** [bridgedb/swagger-webservice#5]
{"messages":["attribute paths.'/{organism}/xrefsBatch'(post).[body].collectionFormat is unexpected"],"schemaValidationMessages":[{"level":"error","domain":"validation","keyword":"anyOf","message":"instance failed to match at least one required schema among 2","schema":{"loadingURI":"http://json-schema.org/draft-04/schema#","pointer":"/properties/type"},"instance":{"pointer":"/definitions/IdList2/type"}}]}

**Comment by nunogit** [comment]
- [x] Check if we are running the latest version on git (maybe with @JonathanMELIUS 
- [x] Solve the issue :)

**Comment by AlexanderPico** [comment]
Still not working:
http://www.bridgedb.org/swagger/#!/Genes/post_organism_xrefsBatch

**Comment by egonw** [comment]
It seems to be failing still... @JonathanMELIUS, I guess you updated the BridgeDb webservice code too, in the update last week, not?

**Comment by egonw** [comment]
They seem to be working (returning results), but the service also seems to have trouble with new lines... I tried `curl -D @inputfile.txt` with DOS and UNIX newlines, but both seem to have issue... Would that explain the results? This `inputfile.txt` works:

```
CHEBI:28499     Ce
```

But this one does not:

```
CHEBI:28499     Ce
CHEBI:28498     Ce
```

The full curl command:

```(shell)
curl -X POST --header 'Content-Type: text/html' --header 'Accept: */*' -d @inputfile.txt 'http://webservice.bridgedb.org/Human/xrefsBatch
```

**Comment by nunogit** [comment]
The problem in swagger.json (webservice json description), is now solved. The error is no longer reported.
The problem with the webservice still exists, but this is a different problem. Might actually be at server level.
I will be opening a new ticket for this.
